# Generated by Django 4.2.2 on 2023-06-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_user_movie_added_by_alter_movie_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
