# Generated by Django 4.2.2 on 2023-06-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_duration_alter_movie_synopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='added_by',
            new_name='user',
        ),
    ]
